- package.json
> Use built-in punycode

- README.md
- lib/cookie.js
- lib/memstore.js
- lib/pathMatch.js
- lib/permuteDomain.js
> Export MemoryCookieStore. Fix #39.

- lib/cookie.js
> Move aliasing of deserializeSync below definition

- README.md
Added links to a few stores that people have written with brief descriptions of what they do.
> Add links to 3rd party stores to the README

- README.md
I think this is all of the modifications that need to be made to the repo to work with Travis after the migration. There may be more to this though; so please pass on some feedback.
> Fixed Travis path after repository migration.

- .gitignore
- .npmignore
- Dockerfile
- docker-compose.yml
Work to dockerize the project. I've only added the two docker-files to .npmignore; not sure if we want to add more files there.
> Dockerized project. Added .npmignore for docker files.

- .travis.yml
> Apr2018 node versions

- package.json
vows updated for https://nodesecurity.io/advisories/118
> Update packages & npm audit fix

- package.json
> Upgrade to punycode 2.1

- package.json
> Downgrade ip-regex dependency to support node 6

- .eslintrc.json
- lib/cookie.js
- lib/memstore.js
- lib/store.js
- test/parsing_test.js
- test/remove_all_test.js
- test/same_site_test.js
Note: this is based on #155 changes. Will rebase and open for review if that one is merged.
> prefer classes over function prototypes to define classes

- README.md
- lib/cookie.js
- test/cookie_prefixes_test.js
- Waiting on #128 to get merged so can use README blurb about draft rfc6265bis
- Would like to get feedback on how to resolve TODO at https://github.com/ShivanKaul/tough-cookie/blob/1fe14103d068edf1536e1e5e4ec85c97db37e3be/lib/cookie.js#L1121
> Add support for cookie prefixes

- Dockerfile
- test/cookie_jar_test.js
Simple test for issue #144 that proves it is not an issue in the codebase. Update Dockerfile to explicitly use Node 12 LTR.
> Awaterma issue#144 property secure

- CHANGELOG.md
- lib/cookie.js
- test/cookie_jar_test.js
Fix for issue #195, I wonder if we should add in the rest of the options to the serialization functions. Thoughts?
> Fix for issue #195

- .github/CODEOWNERS
- .github/dependabot.yml
- Adds a `dependabot.yml` configuration file to get notifications about dependency updates.
- Adds a `CODEOWNERS` file to assign reviewers when PRs are opened.
Closes #299
> Configure dependabot and codeowners

- package.json
> Remove `@types/psl` from dev dependencies

- README.md
Rendered pages:
- https://github.com/salesforce/tough-cookie/blob/v5-docs-readme/README.md
---
Main PR:
- #384
> V5 Docs - README

- .github/workflows/integration.yaml
- api/docs/tough-cookie.version.md
- api/tough-cookie.api.md
- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/jarSerialization.spec.ts
- lib/version.ts
- package-lock.json
- package.json
Includes changes:
https://github.com/salesforce/tough-cookie/compare/4afc5d..72ed3f0
> Preparing for release 5.0.0-rc.2

- .github/workflows/publish.yaml
See https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions
> Give permissions for provenance generation

- api/docs/tough-cookie.version.md
- api/tough-cookie.api.md
- lib/version.ts
- package-lock.json
- package.json
> Prepare v5.1.2

- README.md
- api/docs/tough-cookie.version.md
- api/tough-cookie.api.md
- lib/version.ts
- package-lock.json
- package.json
Includes changes from https://github.com/salesforce/tough-cookie/compare/v5.1.2...prepare_v6
> Prepare v6
