- lib/cookie.js
- test/api_test.js
- test/parsing_test.js
This is basically a proposal for fixing #10 since I came across an instance where I'd need this.
I'm not sure about the handling of the "re-introduced" strict parameter. In order to not change behaviour when not given I set it to default to true for now, but I guess we'd need a better solution here?
> Enable parsing cookies with an empty or no key

- README.md
- lib/cookie.js
- test/cookie_jar_test.js
Forgot that this might be needed too, especially if tough-cookie is used in conjunction with `request`, which doesn't set loose by default.
I was thinking about doing an options object as a param instead, but I don't think that the already existing option can be replaced in a backwards-compatible way, so we could only add an options object in addition. Not sure about what to do here.
> Implement loose mode for cookie jars

- lib/cookie.js
This PR is a resolution of  #63.
At first I thought that I will update the regular expressions such that the value contains either no quotes or exactly two (one at the beginning and one at the end), i.e., COOKIE_PAIR would be something like  `/^(([^=;]+))\s*=\s*(("?)[^"\n\r\0]*\4)/` but then I realized that you have several tests that go against this. Note that these tests violate [RFC6265](https://tools.ietf.org/html/rfc6265#section-4.1.1). This is just heads up, I am leaving up to you whether this is something that you want.
So, eventually I've just simplified the regular expression by removing the misleading (incorrectly implemented) parts that were responsible for the check for the quotes. There are no tests in this PR because the behaviour is the same after this change - it is just a …
> Simplification of (LOOSE_)COOKIE_PAIR regular expressions.

- lib/cookie.js
- test/parsing_test.js
Bug Credit To: David Kirchner <dpk@stream.me>
> Reduce parse time for many semicolons.

- .travis.yml
- README.md
- package.json
- test/parsing_test.js
Restore backwards compatibility to node 0.8 (since that's what `request` supports).
> Restore backwards compatibility to node 0.8

- lib/cookie.js
- test/jar_serialization_test.js
Fix #59
Switched the order of `deepEqual` arguments to match its interface and improve readability of error messages
`assert.deepEqual(actual, expected[, message])`
> CookieJar.deserialize does not modify its input

- .travis.yml
- package.json
Node v7 soft-deprecates the punycode module.
See https://nodejs.org/en/blog/release/v7.0.0/ and
https://github.com/nodejs/node/pull/7941
> Explicit punycode dependency

- README.md
- lib/cookie.js
- test/parsing_test.js
> Constrain spaces before = to 256

- README.md
- lib/cookie.js
- package.json
- test/date_test.js
I have nothing against RegExps in general, but for security conscious code, there's too many pitfalls. 
This pull-request is about converting from using mostly RegExp to using mostly native JavaScript code. The main cookie parser and the RFC-compliant date parser are most affected.
When tough-cookie was originally written, the RegExps were used because it seemed easier to maintain. This pull request certainly increases the code complexity, but does so in the hopes that maintaining the RegExps would have been more time-consuming in the long run.
As a bonus, it seems that the pure JavaScript version is about 1 to 2% faster than the RegExp one, based on the time it takes to run the entire tough-cookie test suite (7.0s versus 6.9s now).
> No RexExp parser

- test/jar_serialization_test.js
So far the error message was not tested when calling `assert.throws`.
In new Node.js versions it is warned in case this is detected.
Now the error message is validated by using a regular expression
instead of the string.
> Fix assert throws assertion

- .gitignore
- .npmignore
- package.json
Pulled in NYC (Istanbul 2.0) into our package.json. Did a few runs with the local package, set it up to do html based coverage reporting (through vows).
> Added NYC coverge and reporting to tough-cookie.

- lib/cookie.js
- lib/memstore.js
From Node.js 11 on custom inspection will not work with the `inspect`
property anymore. This changes it to use the newer custom inspection
symbol if available. To stay backwarts compatible it keeps the old
function in place in case it is called directly by users.
> Fix custom inspection

- lib/cookie.js
- test/jar_serialization_test.js
Fixes #101 and makes it so that the `.cloneSync` method does what the documentation says (i.e., it checks for the new store to be synchronous too!)
> Fix jar clone and cloneSync methods

- .gitignore
- .npmignore
Since this is a module and not an end package, we want CI/etc. to always upgrade packages based on semver.
> Purposefully don't lock dependencies

- lib/cookie.js
- test/cookie_jar_test.js
Addresses #132, partially. The error message is clearer, indicating that
this method only accepts the afformentioned types. The part of 132 that
it doesn't address is the whole "Cookie instance from another version of
the `tough-cookie` package" thing, which isn't really solvable unless we
somehow expose the Cookie class that "belongs to" this CookieJar class,
which is maybe another patch.
> setCookie arg must be Cookie or string

- lib/cookie.js
- package.json
Replace [net.isIP] with [ip-regex].
[ip-regex]: https://github.com/sindresorhus/ip-regex/blob/master/index.js
[net.isIP]: https://github.com/nodejs/node/blob/master/lib/internal/net.js#L7
> Use ip-regex instead of net.isIP. Fix #125

- README.md
- lib/cookie.js
- test/jar_serialization_test.js
- test/parsing_test.js
- test/same_site_test.js
Support for `SameSite` cookies, see #80 and also the other 6265bis issues.
> SameSite Cookies

- lib/cookie.js
Works around https://github.com/facebook/jest/issues/2549 when used in Jest
> fix(cookie-jar): use typeof for checking type of option

- README.md
- lib/cookie.js
- test/cookie_prefixes_test.js
Refer to https://github.com/salesforce/tough-cookie/pull/164
> Re-add cookie prefix feature

- lib/cookie.js
- lib/memstore.js
- package.json
- test/api_test.js
This is based on #155 and #156 . It could use a few more tests, but I wanted to get some feedback before writing any more.
BTW, vows seems dead, and has terrible ergonomics for async tests. Any interest in switching to something else? I'm partial to ava these days, but literally anything would be better than vows. :-)
> return promise if callback not passed to async methods

- lib/cookie.js
- test/regression_test.js
Fixes #175, related to #158 
Functions that are not "instanceof Function" can occur in e.g. Jest tests,
see https://github.com/facebook/jest/issues/2549
This was fixed once before (d94532d), now adding also regression tests
(and fixing same issue in getCookies, too).
> Use typeof for checking type of option

- lib/permuteDomain.js
Fix #174
I think @ruoho said he'd write a test case for #173 - once that is in I'll rebase off of that and add some more tests.
The hack in https://github.com/salesforce/tough-cookie/blob/master/lib/permuteDomain.js#L41 was introduced in #173 and is expanded in this PR because we rely on PSL's `psl.get()` call. This doesn't work for special-use domains because most of them are not in the Public Suffix List (except for `.onion`). Interestingly, `libpsl` (the C equivalent of the PSL js library we use) has a `isCookieDomainAcceptable()` function that would be useful - I raised an issue asking if there's interest in it for the PSL js library here: https://github.com/lupomontero/psl/issues/232
> Add explanation and more special-use domains

- CHANGELOG.md
- lib/cookie.js
Added the rest of the constructor options into the serialized / deserialize functions
> Sync of constructor options for serialization

- lib/cookie.js
- test/cookie_jar_test.js
1. some of the old sites by mistake send a blank cookie, and whenever a blank cookie is encountered, failed to parse cookie error comes up - so I made a fix of checking the length and accordingly calling callback with null value.
Note: Either this fix, or CookieJar constructor needs to take SetCookieOptions too, as ignoreError is part of SetCookieOptions interface
> Returned null in case of empty cookie value

- .gitignore
- lib/cookie.js
- lib/validators.js
- test/parsing_test.js
I think this should provide a fix for issue #11, as well as I can tell. Please take a look.
@medelibero-sfdc @ruoho @ruoho-sfdc @ShivanKaul 
Thanks!
> 132 str trim not a function

- .github/workflows/integration.yaml
Have to make a change to the actions commands; `npm ci` only works if an install has already happened. :)
> Issue #210 -- Updated workflow to use npm install.

- lib/memstore.js
- test/regression_test.js
Also some linter auto-fixes adding noise to the test file. 😐  The test that I added starts on [line 249](https://github.com/salesforce/tough-cookie/pull/226/files#diff-89d2406f54a225979d07ba1f8d09d74faca4628e3b361b22143af303cec307efR249).
> fix: MemoryCookieStore methods should exist on the prototype, not on the class.

- lib/cookie.js
- lib/permuteDomain.js
- lib/pubsuffix-psl.js
- test/api_test.js
This PR adds test cases for the `allowSpecialUseDomain` option introduced in [PR #173](https://github.com/salesforce/tough-cookie/pull/173).  The special use domain check was changed to be a refinement on the public suffix check since both setting and retrieving cookies can fail since not all special use domains are considered public suffixes.
The following cases are tested:
* when the cookie jar is configured with `allowSpecialUseDomain=true`, the code will skip the lookup of a public suffix when a special use domain is detected
* when the cookie jar is configured with `allowSpecialUseDomain=false`, the code will raise an error describing proper usage when a special use domain is detected
Fixes #206
> Unit test cases for `allowSpecialUseDomain` option

- lib/cookie.js
- test/domain_and_path_test.js
The domain match routine can fail in cases where the domain suffix characters can be located in the string before the suffix. Changing the logic to use `lastIndexOf` instead of `indexOf` seems more appropriate for testing the suffix here.
Fixes #235
> fix: domain match routine

- lib/cookie.js
The way the code is right now, it doesn't use the Punycode package, but the internal NodeJS punycode module. That is deprecated now, which is why I saw the warning popping up (for the ones googling this, the warning is `[DEP0040] DeprecationWarning: The 'punycode' module is deprecated. Please use a userland alternative instead`). According to the docs of the Punycode package, you need to use `require('punycode/')`, to use the Punycode package rather than the internal NodeJS module, see https://github.com/mathiasbynens/punycode.js#installation.
> Stop using the internal NodeJS punycode module

- lib/cookie.js
- test/parsing_test.js
- test/same_site_test.js
> fix: distinguish between no samesite and samesite=none

- README.md
- lib/cookie.js
- lib/memstore.js
- test/api_test.js
To avoid breaking behavior the `allowSpecialUseDomain` option should have been set to `true` by default.
This PR also adds tests that cover when a default `CookieStore` is created it does allow cookies with special use domains.
closes #246
> fix: allow special use domains by default

- .eslintrc.json
- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/cookiePrefixes.spec.ts
- lib/__tests__/cookieSorting.spec.ts
- lib/__tests__/cookieToAndFromJson.spec.ts
- lib/__tests__/cookieToString.spec.ts
- lib/__tests__/data/dates/bsd-examples.ts
- lib/__tests__/data/dates/examples.ts
- lib/__tests__/data/parser.ts
- lib/__tests__/ietf.spec.ts
- lib/__tests__/jarSerialization.spec.ts
- lib/__tests__/nodeUtilFallback.spec.ts
- lib/__tests__/parse.spec.ts
- lib/__tests__/regression.spec.ts
- lib/__tests__/removeAll.spec.ts
- lib/__tests__/sameSite.spec.ts
- lib/cookie.ts
- lib/utilHelper.ts
Extending `prettier` extends `eslint-config-prettier`. To leverage the full power of Prettier via `eslint-plugin-prettier`, we should extend `plugin:prettier/recommended`.
> Fix prettier in eslint config

- lib/memstore.js
- test/cookie_jar_test.js
All occurrences of new object creation in `memstore.js` have been changed from `{}` (i.e.; `Object.create(Object.prototype)` to `Object.create(null)` so that we are using object instances that do not have a prototype property that can be polluted.
@fixes #282
> Prevent prototype pollution in cookie memstore

- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/defaultPath.spec.ts
- lib/__tests__/domainMatch.spec.ts
- lib/cookie.ts
- lib/store.ts
Just plucking away at some of the @ts-ignore directives. I didn't address all of them in this PR; some I fixed in #275 and others I wasn't sure what the best solution would be.
> Remove some @ts-ignore directives.

- .eslintrc.json
- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/data/parser.ts
- lib/__tests__/removeAll.spec.ts
- lib/cookie/cookie.ts
- lib/cookie/cookieJar.ts
- lib/memstore.ts
- lib/utils.ts
- lib/validators.ts
- tsconfig.json
Using `arguments` is a known code smell. It is used by `createPromiseCallback` to extract the callback from the last provided argument. However, all calling code already knows which variable contains the callback, so we don't actually need to use `arguments`.
> Avoid using `arguments`

- .github/dependabot.yml
We want @types/node to match the *lowest* version of node.js that we support.
> Configure dependabot to ignore @types/node.

- README.md
Now `lib/memstore.ts` is linked correctly in the documentation after it was migrated to typescript
> docs: use correct memstore file link

- jest.config.ts
- lib/__tests__/cookie.spec.ts
- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/cookieSorting.spec.ts
- lib/__tests__/cookieToAndFromJson.spec.ts
- lib/__tests__/jarSerialization.spec.ts
- lib/__tests__/lifetime.spec.ts
- lib/__tests__/nodeUtilFallback.spec.ts
- lib/cookie/cookie.ts
The `cookie.expiryTime()` method was calculating an `expiry-time` value using `creation-time + max-age` if the `max-age` value was set. This is not correct as RFC6265 does not say anything about `creation-time` having any effect on `max-age`.
The main issue is that `max-age` should be stored as a date (see text below), not an offset number as it currently is implemented.
> 5.2.2.  The Max-Age Attribute
>
> If the attribute-name case-insensitively matches the string "Max-
> Age", the user agent MUST process the cookie-av as follows.
>
> If the first character of the attribute-value is not a DIGIT or a "-"
> character, ignore the cookie-av.
>
> If the remainder of attribute-value contains a non-DIGIT character,
> ignore the cookie-av.
>
> Let delta-seconds be the attribute-value converted …
> Fix expiry time not updating when cookie is updated

- lib/cookie/cookie.ts
- lib/cookie/cookieJar.ts
- lib/cookie/index.ts
- lib/getPublicSuffix.ts
- lib/permuteDomain.ts
- lib/pubsuffix-psl.ts
- package-lock.json
- package.json
One of the topics that came up in discussions for v5 was considering replacements for `psl` (see https://github.com/salesforce/tough-cookie/discussions/255). This PR replaces that library with `tldts` which is more performant.
Fixes #239
Fixes #338
> Replace `psl` with `tldts`

- lib/__tests__/util.spec.ts
- lib/utils.ts
Currently `safeToString([Object.create(null)])` throws, even though it shouldn't. This PR fixes that.
> Handle unlikely edge case in unimportant util

- .npmignore
- package.json
When #296 was merged, the list of files to include in `package.json` was not updated. This PR fixes that.
The `.npmignore` file is also removed because I find it causes some unexpected behaviors like [ignoring the contents of `.gitignore`](https://docs.npmjs.com/cli/v10/using-npm/developers#keeping-files-out-of-your-package). It's a bit of extra work to maintain the allow listed `files` but it's generally safer.
--- 
```
npm notice 
npm notice 📦  tough-cookie@5.0.0-rc.0
npm notice === Tarball Contents === 
npm notice 1.5kB  LICENSE                       
npm notice 33.7kB README.md                     
npm notice 1.8kB  dist/cookie/canonicalDomain.js
npm notice 1.7kB  dist/cookie/constants.js      
npm notice 23.0kB dist/cookie/cookie.js         
npm notice 2.6kB …
```
> Fix allow listed `files` for what to include in npm package

- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/cookieSorting.spec.ts
- lib/cookie/cookie.ts
- package.json
Currently, the props on `Cookie` all have `| undefined`, even though none of them actually ever use `undefined` as a value. If we get rid of `| undefined`, though, we get a TypeScript error complaining that the prop is not definitively assigned in the constructor. This is because we use `Object.assign` to initialize props, and I guess TypeScript just can't quite handle that. So, to get rid of `undefined` as a false possible value, we have to manually assign every prop. A bit more verbose, but not a significant change.
Additionally, the cookie constructor options are identical to the props of `Cookie`, excluding the methods, so I changed the type from explicitly listing everything to just a mapped type, for simpler maintenance. I wasn't sure if that would be a good idea, because sometimes …
> Clean up cookie creation

- .eslintrc.json
- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/jarSerialization.spec.ts
- lib/__tests__/regression.spec.ts
- lib/__tests__/util.spec.ts
- lib/cookie/canonicalDomain.ts
- lib/cookie/cookie.ts
- lib/cookie/cookieCompare.ts
- lib/cookie/cookieJar.ts
- lib/cookie/formatDate.ts
- lib/cookie/parseDate.ts
- lib/memstore.ts
- lib/utils.ts
The primary motivation is to help with #380; enforcing an explicit return type helps us identify which functions return `null` / `undefined` and therefore standardize on one value as much as possible.
A secondary motivation is that it technically makes type checks faster, as parsing function bodies is no longer necessary to infer the return type. However, given the current size/state of our code, there's no discernible performance gain by enforcing this rule.
> Enforce explicit function return type

- package.json
- test/scripts/vows.js
Vows is a legacy test suite, and we plan on removing it eventually, but in the meantime it would be nice if it actually worked. To see the intended output when tests fail, we need to patch `util.patch` and `util.puts`.
> patch removed util methods for vows

- lib/__tests__/cookieToAndFromJson.spec.ts
- lib/__tests__/domainMatch.spec.ts
- lib/__tests__/parse.spec.ts
- lib/cookie/canonicalDomain.ts
- lib/cookie/cookie.ts
- lib/cookie/cookieJar.ts
- lib/cookie/defaultPath.ts
- lib/cookie/domainMatch.ts
- lib/cookie/parseDate.ts
- lib/getPublicSuffix.ts
- lib/memstore.ts
- lib/permuteDomain.ts
- lib/store.ts
- lib/utils.ts
- test/cookie_to_json_test.js
- test/parsing_test.js
This standardizes most of our methods to accept both null and undefined, and mostly return a value or undefined. Exceptions that I noticed are `canonicalDomain`, `getPublicSuffix`, `permuteDomain`, and `domainMatch`, which all return null. I don't remember why I skipped them when I originally did this, so I figured I'd just leave them for now. (I did most of this work a while ago, and evidently never pushed!)
This also introduces a helper type `Nullable<T>` for readability.
nb: #377 but without changes to cookie creation
> clean up usage of null/undefined

- lib/validators.js
Set `toString` to `Object.prototype.toString` as the code implicitly expects, to avoid conflicts with mocked globals. (see issue #405).
> Add local alias for `toString`

- lib/cookie.js
- lib/validators.js
The `getCookies` and `setCookie` functions can handle URL objects. They used to handle it in v4.0.0 but it seems since 4.1.1, validations were added which don't allow using URL object. PR: https://github.com/salesforce/tough-cookie/pull/193
This change updates the validations to allow both string and object.
> Fix incorrect string validation for URL

- api/tough-cookie.api.md
- lib/cookie/cookieJar.ts
- package-lock.json
- package.json
Now that we're a TypeScript project, changing TypeScript version is a breaking change. We only get one TypeScript version per major release, so we should use the latest version, rather than the version that was current when we started moving to TypeScript ages ago.
Code change is a linter fix, I guess due to better type detection.
> Use latest TypeScript version

- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/domainMatch.spec.ts
- lib/cookie/canonicalDomain.ts
- lib/cookie/cookieJar.ts
- package-lock.json
- package.json
- test/cookie_jar_test.js
We originally added url-parse to facilitate using the library with react native. However, there's a [URL polyfill](https://github.com/charpeni/react-native-url-polyfill) that react native users can use, and we don't otherwise support the runtime, so we've decided to remove the dependency (fixes #278).
I also realized that `new URL(str)` also does the same thing as the `punycode` library, so I removed that as well.
> Remove url-parse and punycode

- lib/cookie/cookieJar.ts
This is a follow up into my testing of our latest release candidate against the `jsdom` test suite. The callback issues have been sorted out but I also encountered a validation issue around the `URL` object that is used by `jsdom`. When we are passed a `URL` object, we test it using `url instanceof URL` but the `URL` object from `jsdom` is not the same as the global `URL` object. 
Relying on `instanceof` is always tricky in JavaScript. We should instead favor checking for the structure of the object we expect which must have the following structure:
```ts
type UrlContext = {
hostname: string
pathname: string
protocol: string
}
```
This PR replaces the `instanceof` check with a validation for the above structure. This will pass for unknown `url` values that are instances of `URL` since …
> Checks structure instead of instanceof for URL test

- lib/__tests__/canonicalDomain.spec.ts
- lib/cookie/canonicalDomain.ts
Today I learned that node has a utility, [`domainToASCII`](https://nodejs.org/api/url.html#urldomaintoasciidomain), that converts a domain name to ASCII. We can use that in `canonicalDomain` because we don't need to parse the full URL.
> use `domainToASCII(str)` instead of `new URL(str).hostName`

- lib/__tests__/cookieJar.spec.ts
- lib/cookie/cookieJar.ts
The logic for checking and removing expired cookies fails when the cookie has an expiry date set to the epoch time of `0` (i.e.; `Thu, 01 Jan 1970 00:00:00 GMT`). This is because the branch check that triggers cookie removal was testing `expiryTime` which is `falsy` for a value of `0` and that short-circuits the logic.
This PR updates the logic to narrow the type of `expiryTime` from `number | undefined` to `number` using `expiryTime != undefined` which allows the `0` value to proceed to the subsequent condition and trigger the cookie removal.
Fixes #455
> fix: remove cookies that expire at epoch time of `0`

- lib/pathMatch.ts
> fix(path-match): avoid parsing path as regex

- lib/cookie/canonicalDomain.ts
> revert: use runtime-agnostic `domainToASCII`

- eslint.config.mjs
- package-lock.json
- package.json
This adds a new eslint plugin to avoid node's built in modules, and hopefully help keep our package more cross-platform compatible.
> chore: avoid nodejs modules

- lib/__tests__/domainMatch.spec.ts
- lib/cookie/domainMatch.ts
The code in `domainMatch` needs to make comparisions using the `_str` and `_domStr` variables as these are canonicalized versions of the `domain` and `cookieDomain` arguments.
One of the comparisions was mistakenly using the `cookieDomain` when it should have been using `_domStr`. This PR closes #499 by using the correct variable for the comparison and adds a test that covers this case to our list of cases for `domainMatch`.
> Fix regression bug in `domainMatch`

- lib/__tests__/cookieJar.spec.ts
- lib/__tests__/cookiePrefixes.spec.ts
- lib/cookie/cookieJar.ts
This change was introduce in https://github.com/salesforce/tough-cookie/pull/498. As this new feature was driven by current browser behaviors + updates to the terminology for "secure" connections from RFC6265bis-19, it seemed appropriate to also apply the following check from RFC6265bis-19 when setting a cookie:
> If the request-uri does not denote a "secure" connection (as defined by the user agent), and the cookie's secure-only-flag is true, then abort these steps and ignore the cookie entirely.
> - https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis-19#section-5.7-3.13.1
This deviates from RFC6265 which does not describe any check for a "secure" connection when setting a cookie, only when retrieving the cookie.
In our integration tests for JSDOM, this code also causes a …
> Reverts the check on the Secure attribute when setting a cookie
